"""Added resetToken, tokenUsed, resetTokenCreateAt to user model

Revision ID: d7918d6da680
Revises: 0ea914ea9a5d
Create Date: 2024-10-16 20:03:20.864136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7918d6da680'
down_revision = '0ea914ea9a5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('token_used', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('reset_token_created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('reset_token_created_at')
        batch_op.drop_column('token_used')
        batch_op.drop_column('reset_token')

    # ### end Alembic commands ###
