"""Increased resetToken size to 512

Revision ID: e4e86f6315f3
Revises: d7918d6da680
Create Date: 2024-10-16 20:25:07.058610

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e4e86f6315f3'
down_revision = 'd7918d6da680'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resetToken', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('tokenUsed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('resetTokenCreatedAt', sa.DateTime(), nullable=True))
        batch_op.drop_column('token_used')
        batch_op.drop_column('reset_token')
        batch_op.drop_column('reset_token_created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token_created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('reset_token', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('token_used', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('resetTokenCreatedAt')
        batch_op.drop_column('tokenUsed')
        batch_op.drop_column('resetToken')

    # ### end Alembic commands ###
